name: assert util types release
on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
      - run: pnpm install
      - name: execute vitest
      - run: pnpm run test run
      - run: pnpm run build
